import styles from './work.module.scss'

export const metadata = {
  title: 'Demo About',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <main className={styles.container}>
      
      <h1>Hola About</h1>
    </main>
  )
}
